const titles={dashboard:["总览","425 省道 / 涉铁架梁 / V1.0"],projects:["项目台账","项目基础信息 / 桥跨施工类别"],plans:["作业计划","封锁/邻营计划"],process:["工序检查","架桥机过孔 / 运梁喂梁 / 落梁复核"],risks:["隐患整改","风险登记 / 整改复查 / 闭环状态"],reports:["资料导出","台账 / 检查表 / 整改记录"]};
const roleRules={worker:{label:"施工人员",note:"只能查看信息、提交和查看问题反馈",submits:["feedback"],reviews:[]},manager:{label:"现场管理人员",note:"可提交反馈和施工进展，提交后等待项目负责人审核",submits:["feedback","process","plan","risk"],reviews:[]},leader:{label:"项目负责人",note:"只审核确认或退回整改，不提交反馈和施工进展",submits:[],reviews:["feedback","process","plan","risk"]}};
const processOrder=["pre","beam","land"],spanOrder=["第 19 跨","第 20 跨","第 21 跨"],processStepMap={pre:"block",beam:"pass",land:"land"},stepProcessMap={block:"pre",pass:"beam",land:"land"},stepLabel={block:"封锁/防护",pass:"过孔",land:"落梁"},tabLabel={pre:"过孔准备",beam:"运梁喂梁",land:"落梁复核"};
const statusOptions=["未开始","管理人员已提交","负责人已确认","退回整改"],riskStatusOptions=["未开始","管理人员已提交"];
const processItems={pre:["架桥机检测证书、操作人员证件已核验","前中后支腿落位、支垫和锁定状态已检查","接地保护、吊具、钢丝绳和限位装置已检查","封锁命令、停电单元、驻站联络已确认"],beam:["运梁车走行线和防溜措施已确认","箱梁捆绑、护角和吊点状态已检查","喂梁过程指挥信号、人员站位已确认","桥面材料清理完成，无侵限物品"],land:["梁体中心线、梁端线和支座位置已复核","落梁过程四点受力平稳，无偏压","临时支座、限位挡块和防横移措施已设置","工完料净，工具材料清点完成"]};
const defaultPlans=[{purpose:"铁路跨过孔与架梁请点",span:"第 20 跨",type:"Ⅱ级封锁",duration:"120 min",power:"需要",coord:"驻站、停电、设备单位到场",status:"管理人员已提交",auditStatus:"待负责人审核"},{purpose:"邻跨边梁架设计划确认",span:"第 21 跨",type:"Ⅲ级封锁",duration:"120 min",power:"需要",coord:"边梁吊装、防坠落、防侵限",status:"未开始",auditStatus:"未提交"},{purpose:"湿接缝及横隔板点内作业",span:"第 20 跨",type:"Ⅲ级封锁",duration:"120 min",power:"需要",coord:"模板防坠、接触网防污染",status:"负责人已确认",auditStatus:"负责人已确认"}];
const defaultSpanFlows=[{span:"第 19 跨",name:"铁路邻跨架梁",category:"邻营 B 类",steps:{block:"负责人已确认",pass:"负责人已确认",land:"负责人已确认"},auditStatus:"负责人已确认"},{span:"第 20 跨",name:"铁路跨架梁",category:"Ⅱ级封锁",steps:{block:"管理人员已提交",pass:"未开始",land:"未开始"},auditStatus:"进行中"},{span:"第 21 跨",name:"邻跨架梁",category:"Ⅲ级封锁/邻营",steps:{block:"未开始",pass:"未开始",land:"未开始"},auditStatus:"未提交"}];
const defaultRisks=[{type:"机械侵限",position:"第 20 跨桥面",desc:"复核架桥机支腿及运梁车走行线",owner:"设备负责人",due:"2026-07-08",status:"管理人员已提交",auditStatus:"待负责人审核"},{type:"飘浮物",position:"桥面作业区",desc:"轻质材料集中入箱并绑扎固定",owner:"现场防护员",due:"2026-07-07",status:"未开始",auditStatus:"未提交"},{type:"动火焊渣",position:"湿接缝作业点",desc:"铺设防火毯并办理动火审批",owner:"施工负责人",due:"2026-07-06",status:"已闭环",auditStatus:"负责人已确认"}];
function clone(v){return JSON.parse(JSON.stringify(v))}
function makeCheck(span,tab,businessStatus="未开始",auditStatus="未提交"){return{span,tab,checker:"安全员",date:"2026-07-06",businessStatus,auditStatus,submitter:"",reviewer:"",reviewComment:"",items:processItems[tab].map(item=>({item,status:"合格",remark:""}))}}
function makeDefaultProcessChecks(){const checks={};spanOrder.forEach(span=>processOrder.forEach(tab=>checks[`${span}__${tab}`]=makeCheck(span,tab)));processOrder.forEach(tab=>checks[`第 19 跨__${tab}`]=makeCheck("第 19 跨",tab,"负责人已确认","负责人已确认"));checks["第 20 跨__pre"]=makeCheck("第 20 跨","pre","管理人员已提交","待负责人审核");return checks}
let appState={processChecks:makeDefaultProcessChecks(),feedbacks:[],user:null,plans:clone(defaultPlans),spanFlows:clone(defaultSpanFlows),risks:clone(defaultRisks)};
let currentProcessTab="pre",highlightTimer=null,riskFormOpen=false;
function showToast(text){const t=document.getElementById("toast");if(!t)return;t.textContent=text;t.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove("show"),1800)}
function esc(v){return String(v??"").replace(/[&<>"]/g,s=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[s]))}
function tagClass(s){return["负责人已确认","已闭环","审核通过","确认解决"].includes(s)?"green":["待整改","退回整改","负责人退回"].includes(s)?"red":["未开始","未提交","已受理"].includes(s)?"gray":"orange"}
function tag(s){return`<span class="tag ${tagClass(s)}">${esc(s)}</span>`}
function getRole(){return roleSelect.value}
function currentUserName(){return appState.user?.name||loginName.value||"未登录"}
function canView(role,module){return Boolean(roleRules[role]&&module)}
function canSubmit(role,itemType){return roleRules[role]?.submits.includes(itemType)}
function canReview(role,itemType){return roleRules[role]?.reviews.includes(itemType)}
function extractSpan(text){return spanOrder.find(span=>String(text||"").includes(span.replace(/ /g,""))||String(text||"").includes(span))||"第 20 跨"}
function isConfirmed(span,tab){return appState.processChecks[`${span}__${tab}`]?.auditStatus==="负责人已确认"}
function isFlowConfirmed(span){return processOrder.every(tab=>isConfirmed(span,tab))}
function isSpanComplete(span){return processOrder.every(tab=>isConfirmed(span,tab))}
function isSpanOpen(span){const idx=spanOrder.indexOf(span);return idx<=0||isSpanComplete(spanOrder[idx-1])}
function isProcessStageEnabled(span,tab){if(!isSpanOpen(span))return false;if(tab==="pre")return true;if(tab==="beam")return isConfirmed(span,"pre");if(tab==="land")return isConfirmed(span,"beam");return true}
function canEditByTimeline(item){if(!item)return true;const span=item.span||extractSpan(item.position||item.label||"");if(item.tab)return isProcessStageEnabled(span,item.tab);if(item.step)return isProcessStageEnabled(span,stepProcessMap[item.step]);return isSpanOpen(span)}
function getFlowStepOptions(role,currentValue){if(role==="manager")return["未开始","管理人员已提交"];return[currentValue||"未开始"]}
function isFlowSpanOpen(span){const idx=spanOrder.indexOf(span);if(idx<=0)return true;const prev=appState.spanFlows.find(x=>x.span===spanOrder[idx-1]);return prev?.steps?.land==="负责人已确认"}
function isFlowStepOpen(span,step){if(!isFlowSpanOpen(span))return false;const flow=appState.spanFlows.find(x=>x.span===span);if(step==="block")return true;if(step==="pass")return flow?.steps?.block==="负责人已确认";if(step==="land")return flow?.steps?.pass==="负责人已确认";return false}
function canEditFlowStep(role,span,step,currentValue){return role==="manager"&&currentValue!=="负责人已确认"&&isFlowStepOpen(span,step)}
function isManagerFlowValue(value){return["未开始","管理人员已提交"].includes(value)}
function isManagerRiskValue(value){return riskStatusOptions.includes(value)}
function riskDraftStatus(status){return isManagerRiskValue(status)?status:"管理人员已提交"}
function isBlankRisk(r){return !["type","position","desc","owner","due"].some(k=>String(r?.[k]||"").trim())}
function normalizeRisks(risks){return (Array.isArray(risks)?risks:[]).filter(r=>!isBlankRisk(r))}
function isPendingStatus(s){return s==="待负责人审核"||s==="待项目负责人审核"}
function isFinalConfirmedStatus(s){return s==="负责人已确认"||s==="已闭环"}
function isProcessConfirmed(span,tab){return appState.processChecks[`${span}__${tab}`]?.auditStatus==="负责人已确认"}
function canEditProcessCheck(role,span,tab){return canSubmit(role,"process")&&isProcessStageEnabled(span,tab)&&!isProcessConfirmed(span,tab)}
function checkKey(span=checkSpan?.value||"第 20 跨",tab=currentProcessTab){return`${span}__${tab}`}
function getCurrentCheck(){return appState.processChecks[checkKey()]||makeCheck(checkSpan?.value||"第 20 跨",currentProcessTab)}
function switchView(id){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===id));document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===id));pageTitle.textContent=titles[id][0];pageCrumb.textContent=titles[id][1]}
function getCurrentChecklistData(){return Array.from(document.querySelectorAll("#checklist .check-row")).map((row,i)=>({item:processItems[currentProcessTab][i],status:row.querySelector("input[type='radio']:checked")?.value||"合格",remark:row.querySelector("input[data-remark]")?.value||""}))}
function collectCurrentChecklist({keepStatus=true}={}){if(!document.getElementById("checklist")||!checkSpan||!isProcessStageEnabled(checkSpan.value,currentProcessTab))return;const prev=getCurrentCheck();if(prev.auditStatus==="负责人已确认")return;appState.processChecks[checkKey()]={...prev,span:checkSpan.value,tab:currentProcessTab,checker:checker.value,date:checkDate.value,items:getCurrentChecklistData(),businessStatus:keepStatus?prev.businessStatus:"管理人员已提交",auditStatus:keepStatus?prev.auditStatus:"待负责人审核"}}
function syncSpanFlowFromProcess(span){const flow=appState.spanFlows.find(x=>x.span===span);if(!flow)return;const previousAudit=flow.auditStatus;processOrder.forEach(tab=>{const c=appState.processChecks[`${span}__${tab}`];flow.steps[processStepMap[tab]]=c?.auditStatus==="负责人已确认"?"负责人已确认":isPendingStatus(c?.auditStatus)?"管理人员已提交":c?.auditStatus==="负责人退回"?"管理人员已提交":"未开始"});const audits=processOrder.map(tab=>appState.processChecks[`${span}__${tab}`]?.auditStatus||"未提交"),hasRejected=audits.some(x=>x==="负责人退回");const derivedAudit=audits.every(x=>x==="负责人已确认")?"负责人已确认":audits.some(x=>isPendingStatus(x))?"进行中":hasRejected?"负责人退回":audits.some(x=>x==="负责人已确认")?"进行中":"未提交";flow.auditStatus=isPendingStatus(previousAudit)&&!hasRejected&&derivedAudit!=="负责人已确认"?"待负责人审核":derivedAudit}function syncProcessChecksFromSpanFlows(){appState.spanFlows.forEach(flow=>{processOrder.forEach(tab=>{const key=`${flow.span}__${tab}`,check=appState.processChecks[key]||makeCheck(flow.span,tab),stepStatus=flow.steps?.[processStepMap[tab]];if(check.auditStatus==="负责人已确认")return;if(stepStatus==="负责人已确认"){check.businessStatus="负责人已确认";check.auditStatus="负责人已确认";check.reviewer=check.reviewer||"项目负责人";check.reviewComment=check.reviewComment||"由三跨架梁主流程同步";appState.processChecks[key]=check}else if(stepStatus==="管理人员已提交"&&check.auditStatus==="未提交"){check.businessStatus="管理人员已提交";check.auditStatus="待负责人审核";appState.processChecks[key]=check}})})}
function flowStepStatus(span,step){const tab=stepProcessMap[step],check=appState.processChecks[`${span}__${tab}`];if(!check)return"未开始";if(check.auditStatus==="负责人已确认")return"负责人已确认";if(check.auditStatus==="负责人退回")return"退回整改";if(isPendingStatus(check.auditStatus))return"待负责人审核";return check.businessStatus||"未开始"}
function flowOverallStatus(span){const statuses=Object.keys(stepProcessMap).map(step=>flowStepStatus(span,step));if(statuses.every(s=>s==="负责人已确认"))return"负责人已确认";if(statuses.some(s=>s==="退回整改"))return"负责人退回";if(statuses.some(s=>s==="待负责人审核"||s==="管理人员已提交"))return"进行中";return"未提交"}
function nextFlowTab(span){return processOrder.find(tab=>!isConfirmed(span,tab)&&isProcessStageEnabled(span,tab))||"pre"}
function renderCheckStatus(){const c=getCurrentCheck();checkBusinessStatus.textContent=c.businessStatus||"未开始";checkAuditStatus.textContent=c.auditStatus||"未提交";checkReviewComment.value=c.reviewComment||""}
function renderProcessTabs(){const span=checkSpan.value;const available=processOrder.filter(tab=>isProcessStageEnabled(span,tab));if(!available.includes(currentProcessTab))currentProcessTab=available[0]||"pre";document.querySelectorAll("[data-process-tab]").forEach(btn=>{const enabled=isProcessStageEnabled(span,btn.dataset.processTab);btn.disabled=!enabled;btn.classList.toggle("active",btn.dataset.processTab===currentProcessTab);btn.classList.toggle("locked-control",!enabled)})}
function setProcessControls(enabled){const role=getRole(),current=getCurrentCheck(),pending=isPendingStatus(current.auditStatus),editable=enabled&&canEditProcessCheck(role,checkSpan.value,currentProcessTab);checklist.querySelectorAll("input").forEach(input=>input.disabled=!editable);[checker,checkDate].forEach(input=>{if(input)input.disabled=!editable});submitCheck.disabled=!editable;approveCheck.disabled=!enabled||!pending||!canReview(role,"process");rejectCheck.disabled=!enabled||!pending||!canReview(role,"process");submitCheck.classList.toggle("is-disabled",submitCheck.disabled);approveCheck.classList.toggle("is-disabled",approveCheck.disabled);rejectCheck.classList.toggle("is-disabled",rejectCheck.disabled)}
function renderChecklist(type=currentProcessTab){currentProcessTab=type;renderProcessTabs();const enabled=isProcessStageEnabled(checkSpan.value,currentProcessTab),saved=getCurrentCheck();checklist.innerHTML="";processItems[currentProcessTab].forEach((item,i)=>{const it=saved.items?saved.items[i]:null,st=it?it.status:"合格",rm=it?it.remark:"";const row=document.createElement("div");row.className="check-row";row.innerHTML=`<div><strong>${i+1}. ${esc(item)}</strong></div><div class="radio-group"><label><input type="radio" name="check-${currentProcessTab}-${i}" value="合格" ${st==="合格"?"checked":""}>合格</label><label><input type="radio" name="check-${currentProcessTab}-${i}" value="整改" ${st==="整改"?"checked":""}>整改</label><label><input type="radio" name="check-${currentProcessTab}-${i}" value="不适用" ${st==="不适用"?"checked":""}>不适用</label></div><input class="input" data-remark="${i}" placeholder="备注" value="${esc(rm)}">`;checklist.appendChild(row)});if(saved.checker)checker.value=saved.checker;if(saved.date)checkDate.value=saved.date;document.querySelector("#process .panel")?.setAttribute("data-review-key",`process:${checkSpan.value}:${currentProcessTab}`);renderCheckStatus();setProcessControls(enabled)}
function spanStageState(span){const checks=processOrder.map(tab=>appState.processChecks[`${span}__${tab}`]),flow=appState.spanFlows.find(f=>f.span===span);if(isSpanComplete(span))return"done";if(checks.some(c=>c&&c.auditStatus!=="未提交")||(flow&&flow.auditStatus!=="未提交"))return"doing";return"todo"}
function closeoutStageState(){const spansDone=spanOrder.every(span=>isSpanComplete(span));if(!spansDone)return"todo";const hasPending=getPendingReviewItems().length>0,hasOpenRisk=appState.risks.some(r=>r.status!=="已闭环"||r.auditStatus!=="负责人已确认");return hasPending||hasOpenRisk?"doing":"done"}function renderTimeline(){if(!timelineList)return;const data=[["01","施工准备","桥跨台账、人员、防护、设备资料","done"],["02","第 19 跨","邻营过孔与箱梁架设",spanStageState("第 19 跨")],["03","第 20 跨","铁路跨封锁、停电、过孔架梁",spanStageState("第 20 跨")],["04","第 21 跨","邻跨封锁/邻营配合架梁",spanStageState("第 21 跨")],["05","桥面附属","湿接缝、横隔板、防撞墙、防抛网",spanStageState("第 21 跨")==="done"?"doing":"todo"],["06","资料闭环","检查记录、隐患整改、负责人审核",closeoutStageState()]];timelineList.innerHTML=data.map(x=>`<div class="timeline-node ${x[3]}"><div class="timeline-kicker">${x[0]}</div><div class="timeline-title">${x[1]}</div><div class="timeline-desc">${x[2]}</div></div>`).join("")}
function renderBridge(){const label={done:"已完成",doing:"施工中",todo:"未施工"};spanOrder.forEach((span,i)=>{const el=document.querySelector(`.beam.b${19+i}`);if(!el)return;const st=spanStageState(span);el.classList.remove("done","doing","todo");el.classList.add(st);const text=el.querySelector(".beam-label");if(text)text.textContent=`第 ${19+i} 跨 ${label[st]}`})}
function renderPlans(){if(!planBody)return;const role=getRole();planBody.innerHTML=appState.plans.map((p,i)=>{const open=canEditByTimeline({span:p.span}),locked=isFinalConfirmedStatus(p.auditStatus)||isFinalConfirmedStatus(p.status),editable=canSubmit(role,"plan")&&open&&!locked,pending=isPendingStatus(p.auditStatus),review=canReview(role,"plan")&&pending;return`<tr data-review-key="plan:${i}"><td contenteditable="${editable}" data-plan="${i}" data-field="purpose">${esc(p.purpose)}</td><td contenteditable="${editable}" data-plan="${i}" data-field="span">${esc(p.span)}</td><td><div contenteditable="${editable}" data-plan="${i}" data-field="type">${esc(p.type)}</div><div class="muted-small" contenteditable="${editable}" data-plan="${i}" data-field="duration">${esc(p.duration)}</div></td><td><div contenteditable="${editable}" data-plan="${i}" data-field="power">${esc(p.power)}</div><div class="muted-small" contenteditable="${editable}" data-plan="${i}" data-field="coord">${esc(p.coord)}</div></td><td>${tag(p.status)}</td><td>${tag(p.auditStatus)}</td><td>${review?`<button class="btn primary" type="button" data-plan-approve="${i}">审核通过</button><button class="btn danger" type="button" data-plan-reject="${i}">退回整改</button>`:`<button class="btn" type="button" data-plan-submit="${i}" ${editable?"":"disabled"}>提交</button>`}</td></tr>`}).join("");updateEntryLocks()}
function renderSpanFlows(){if(!spanFlowTable)return;spanFlowTable.innerHTML=`<div class="span-flow-row header"><div>桥跨</div><div>封锁/防护</div><div>过孔</div><div>落梁</div><div>总体状态</div><div>操作</div></div>`+appState.spanFlows.map((s,i)=>{const overall=flowOverallStatus(s.span),tab=nextFlowTab(s.span);return`<div class="span-flow-row" data-review-key="flow:${i}"><div><div class="span-name">${esc(s.span)}：${esc(s.name)}</div><div class="span-desc">${esc(s.category)}｜状态来源：工序检查</div></div>${["block","pass","land"].map(k=>`${tag(flowStepStatus(s.span,k))}<div class="muted-small">${tabLabel[stepProcessMap[k]]}</div>`).join("")}<div>${tag(overall)}</div><div><button class="btn" type="button" data-flow-jump="${i}" data-tab="${tab}">进入工序检查</button></div></div>`}).join("")}
function renderRisks(){if(!riskList)return;appState.risks=normalizeRisks(appState.risks);const role=getRole();riskList.innerHTML=`<div class="risk-row header"><div>风险/位置</div><div>整改要求</div><div>责任/期限</div><div>状态</div><div>操作</div></div>`+appState.risks.map((r,i)=>{const open=canEditByTimeline({position:r.position}),locked=r.auditStatus==="负责人已确认"||r.status==="已闭环",editable=canSubmit(role,"risk")&&open&&!locked,pending=isPendingStatus(r.auditStatus),review=canReview(role,"risk")&&pending,statusText=`<div class="status-pair">${tag(r.status)}${tag(r.auditStatus)}</div>`,submitText=r.auditStatus==="负责人退回"||r.status==="退回整改"?"重新提交":"提交整改";return`<div class="risk-row" data-review-key="risk:${i}"><div class="risk-main"><div class="risk-title">${esc(r.type)}</div><div class="risk-meta">${esc(r.position)}</div></div><div>${esc(r.desc)}</div><div><div>${esc(r.owner)}</div><div class="risk-meta">${esc(r.due)}</div></div><div>${statusText}</div><div>${review?`<button class="btn primary" type="button" data-risk-approve="${i}">审核通过</button><button class="btn danger" type="button" data-risk-reject="${i}">退回整改</button>`:`<button class="btn" type="button" data-risk-submit="${i}" ${editable?"":"disabled"}>${submitText}</button>`}</div></div>`}).join("");riskMetric.textContent=appState.risks.filter(r=>r.status!=="已闭环").length;updateEntryLocks()}
function updateTopbarIdentity(){const p=document.getElementById("topProjectName"),r=document.getElementById("roleDisplay");if(p&&projectName)p.textContent=projectName.value||"425 省道上跨阜淮铁路桥梁工程";if(r)r.textContent=roleRules[getRole()]?.label||"未登录"}function updateProjectReadonly(){const leader=getRole()==="leader";[projectName,railMile,station].forEach(el=>{if(el)el.disabled=!leader});if(addSpanBtn)addSpanBtn.disabled=!leader;updateTopbarIdentity()}
function getPendingReviewItems(){const items=[];Object.values(appState.processChecks).forEach(c=>{if(isPendingStatus(c.auditStatus))items.push({type:"process",key:`process:${c.span}:${c.tab}`,view:"process",title:`工序检查-${c.span}-${tabLabel[c.tab]}`,meta:`${c.checker||"安全员"}提交，等待负责人审核`,span:c.span,tab:c.tab})});appState.plans.forEach((p,i)=>{if(isPendingStatus(p.auditStatus))items.push({type:"plan",key:`plan:${i}`,view:"plans",title:`作业计划-${p.span}-${p.type}`,meta:p.purpose,index:i})});appState.risks.forEach((r,i)=>{if(isPendingStatus(r.auditStatus))items.push({type:"risk",key:`risk:${i}`,view:"risks",title:`隐患整改-${r.position}`,meta:r.desc,index:i})});appState.feedbacks.forEach((f,i)=>{if(isPendingStatus(f.status))items.push({type:"feedback",key:`feedback:${i}`,view:"feedback",title:`问题反馈-${f.span}`,meta:`${f.name||"未填姓名"}：${f.text}`,index:i})});return items}
function isTrackingStatus(auditStatus,status){return isPendingStatus(auditStatus)||isPendingStatus(status)||["负责人退回","退回整改"].includes(auditStatus)||["管理人员已提交","整改已提交","退回整改"].includes(status)}
function trackingStatusText(auditStatus,status){if(auditStatus==="负责人退回"||auditStatus==="退回整改"||status==="退回整改")return"退回整改";if(isPendingStatus(auditStatus)||isPendingStatus(status)||status==="管理人员已提交"||status==="整改已提交")return"待负责人审核";return auditStatus||status||"已提交"}
function getTrackingItems(){const items=[];Object.values(appState.processChecks).forEach(c=>{if(isTrackingStatus(c.auditStatus,c.businessStatus))items.push({type:"process",key:`process:${c.span}:${c.tab}`,view:"process",title:`工序检查-${c.span}-${tabLabel[c.tab]}`,meta:`状态：${trackingStatusText(c.auditStatus,c.businessStatus)}`,status:trackingStatusText(c.auditStatus,c.businessStatus),span:c.span,tab:c.tab})});appState.plans.forEach((p,i)=>{if(isTrackingStatus(p.auditStatus,p.status))items.push({type:"plan",key:`plan:${i}`,view:"plans",title:`作业计划-${p.span}-${p.type}`,meta:`${p.purpose}｜${trackingStatusText(p.auditStatus,p.status)}`,status:trackingStatusText(p.auditStatus,p.status),index:i})});appState.risks.forEach((r,i)=>{if(isTrackingStatus(r.auditStatus,r.status))items.push({type:"risk",key:`risk:${i}`,view:"risks",title:`隐患整改-${r.position}`,meta:`${r.desc}｜${trackingStatusText(r.auditStatus,r.status)}`,status:trackingStatusText(r.auditStatus,r.status),index:i})});appState.feedbacks.forEach((f,i)=>{if(isTrackingStatus(f.status,f.status))items.push({type:"feedback",key:`feedback:${i}`,view:"feedback",title:`问题反馈-${f.span}`,meta:`${f.name||"未填姓名"}：${f.text}｜${trackingStatusText(f.status,f.status)}`,status:trackingStatusText(f.status,f.status),index:i})});return items}
function getFloatingItems(){const role=getRole();if(role==="leader")return getPendingReviewItems();if(role==="manager")return getTrackingItems();return[]}
function updateReviewChrome(items=getFloatingItems()){const role=getRole(),hidden=role==="worker";if(reviewToggle){reviewToggle.style.display=hidden?"none":"";reviewToggle.innerHTML=`${role==="manager"?"提交跟踪":"待审"} <span class="review-count" id="reviewCount">${items.length}</span>`}if(reviewPanel){reviewPanel.style.display=hidden?"none":"";if(hidden)reviewPanel.classList.remove("open");const title=reviewPanel.querySelector(".panel-title");if(title)title.textContent=role==="manager"?"提交跟踪":"待审核中心";const tagEl=reviewPanel.querySelector(".tag");if(tagEl)tagEl.textContent=role==="manager"?"点击查看":"点击定位"}}
function renderReviewCenter(){const items=getFloatingItems();updateReviewChrome(items);const countEl=document.getElementById("reviewCount");if(countEl)countEl.textContent=items.length;if(pendingMetric)pendingMetric.textContent=getPendingReviewItems().length;if(!reviewList)return;if(getRole()==="worker"){reviewList.innerHTML="";return}if(!items.length){reviewList.innerHTML=`<div class="feedback-item"><div class="feedback-meta">暂无${getRole()==="manager"?"提交跟踪":"待审核事项"}</div>${getRole()==="manager"?"当前没有待跟踪或退回的提交事项。":"当前没有需要项目负责人处理的内容。"}</div>`;return}reviewList.innerHTML=items.map((it,i)=>`<button class="review-item" type="button" data-review-jump="${it.key}"><span class="review-no">${i+1}</span><span><span class="review-title">${esc(it.title)}</span><span class="review-meta">${esc(it.meta)}</span></span><span class="tag ${getRole()==="manager"?tagClass(it.status||""):"orange"}">${getRole()==="manager"?(it.status||"查看"):"定位"}</span></button>`).join("")}
function renderMetrics(){if(pendingMetric)pendingMetric.textContent=getPendingReviewItems().length}
function updateRiskFormVisibility(){const role=getRole(),canOpen=canSubmit(role,"risk"),form=document.getElementById("riskForm"),head=document.getElementById("riskSubmitHead"),btn=document.getElementById("toggleRiskForm");if(!canOpen)riskFormOpen=false;if(head)head.classList.toggle("is-hidden",!canOpen);if(form){form.classList.toggle("is-open",canOpen&&riskFormOpen);form.classList.toggle("is-collapsed",!canOpen||!riskFormOpen)}if(btn)btn.textContent=riskFormOpen?"收起填写":"展开填写"}function updateEntryLocks(){const role=getRole();const planOpen=canSubmit(role,"plan")&&canEditByTimeline({span:planSpan?.value});[planPurpose,planType,planDuration,planPower,planCoord].forEach(el=>{if(el)el.disabled=!planOpen});if(planSpan)planSpan.disabled=!canSubmit(role,"plan");if(addPlan)addPlan.disabled=!planOpen;const riskOpen=canSubmit(role,"risk")&&canEditByTimeline({position:riskPosition?.value});[riskType,riskDesc,riskOwner,riskDue,riskStatus].forEach(el=>{if(el)el.disabled=!riskOpen});if(riskPosition)riskPosition.disabled=!canSubmit(role,"risk");if(addRisk)addRisk.disabled=!riskOpen;updateRiskFormVisibility()}
function renderAllDynamic(){renderBridge();renderTimeline();renderPlans();renderSpanFlows();renderRisks();updateProjectReadonly();updateEntryLocks();renderReviewCenter();renderMetrics()}
function updateFeedbackForm(){const leader=getRole()==="leader";[feedbackName,feedbackDate,feedbackSpan,feedbackText].forEach(el=>{if(el)el.disabled=leader});submitFeedback.disabled=leader;submitFeedback.classList.toggle("is-disabled",leader);submitFeedback.textContent=leader?"项目负责人请审核下方反馈":"提交反馈"}
function renderFeedbacks(){if(!feedbackList)return;updateFeedbackForm();if(!appState.feedbacks.length){feedbackList.innerHTML=`<div class="feedback-item"><div class="feedback-meta">暂无反馈</div>施工人员和管理人员可在这里提交源头问题。</div>`;return}const can=canReview(getRole(),"feedback");feedbackList.innerHTML=appState.feedbacks.map((x,i)=>{const status=x.status||"待负责人审核",actions=can&&isPendingStatus(status)?`<div class="feedback-actions"><button class="btn primary" type="button" data-feedback-approve="${i}">审核通过</button><button class="btn" type="button" data-feedback-reject="${i}">退回整改</button></div>`:"";return`<div class="feedback-item" data-review-key="feedback:${i}"><div class="feedback-meta">${esc(x.date)} · ${esc(x.name||"未填姓名")} · ${esc(x.span)} · ${tag(status)}</div><div>${esc(x.text)}</div>${x.reviewComment?`<div class="feedback-meta">审核意见：${esc(x.reviewComment)}</div>`:""}${actions}</div>`}).join("")}
function highlightReviewKey(key){clearTimeout(highlightTimer);document.querySelectorAll(".review-highlight").forEach(el=>el.classList.remove("review-highlight"));const el=document.querySelector(`[data-review-key="${CSS.escape(key)}"]`);if(el){el.classList.add("review-highlight");el.scrollIntoView({behavior:"smooth",block:"center"});highlightTimer=setTimeout(()=>el.classList.remove("review-highlight"),2600)}}
function jumpToReviewItem(key){const item=getFloatingItems().find(x=>x.key===key)||getPendingReviewItems().find(x=>x.key===key)||getTrackingItems().find(x=>x.key===key);if(!item)return showToast("该待审核事项已处理");if(item.type==="feedback"){feedbackPanel.classList.add("open");renderFeedbacks();setTimeout(()=>highlightReviewKey(key),60);return}switchView(item.view);if(item.type==="process"){checkSpan.value=item.span;currentProcessTab=item.tab;renderChecklist(item.tab)}else{renderAllDynamic()}setTimeout(()=>highlightReviewKey(key),60)}
function getTableRows(id){return Array.from(document.querySelectorAll(`#${id} tr`)).map(r=>Array.from(r.cells).map(c=>c.innerHTML))}
function setTableRows(id,rows){const b=document.getElementById(id);if(b)b.innerHTML=rows.map(cells=>`<tr>${cells.map(c=>`<td>${c}</td>`).join("")}</tr>`).join("")}
const LOCAL_STATE_KEY="liangSafetyPrototypeState",API_STATE_URL="/api/state";let remoteSyncTimer=null,remoteSyncReady=false;
function normalizeSnapshot(s){if(!s)return null;const next={...s};if(Array.isArray(next.feedbacks))next.feedbacks=next.feedbacks.map(f=>({...f,status:f.status==="已提交"||f.status==="待项目负责人审核"?"待负责人审核":(f.status||"待负责人审核")}));if(Array.isArray(next.risks))next.risks=normalizeRisks(next.risks.map(r=>{const item={...r};if(item.status==="整改已提交")item.status="管理人员已提交";if(item.status==="已上报"||item.status==="整改中"){item.status="未开始";if(isPendingStatus(item.auditStatus))item.auditStatus="未提交"}return item}));return next}
function makeSharedStateSnapshot(){return{projectName:projectName.value,railMile:railMile.value,station:station.value,spans:getTableRows("spanBody"),processChecks:appState.processChecks,feedbacks:appState.feedbacks,plans:appState.plans,spanFlows:appState.spanFlows,risks:appState.risks,savedAt:new Date().toISOString()}}
function applyStateSnapshot(snapshot,{includeUser=false}={}){const s=normalizeSnapshot(snapshot);if(!s)return;if(includeUser&&s.user)appState.user=s.user;if(includeUser&&s.role)roleSelect.value=s.role;if(s.projectName)projectName.value=s.projectName;if(s.railMile)railMile.value=s.railMile;if(s.station)station.value=s.station;if(Array.isArray(s.spans))setTableRows("spanBody",s.spans);if(s.processChecks)appState.processChecks={...makeDefaultProcessChecks(),...s.processChecks};if(Array.isArray(s.feedbacks))appState.feedbacks=s.feedbacks;if(Array.isArray(s.plans))appState.plans=s.plans;if(Array.isArray(s.spanFlows))appState.spanFlows=s.spanFlows;syncProcessChecksFromSpanFlows();if(Array.isArray(s.risks))appState.risks=s.risks}
function renderAfterStateLoad(){renderAllDynamic();renderChecklist(currentProcessTab);renderFeedbacks();updateTopbarIdentity()}
function saveLocalState(shared){const localState={...shared,user:appState.user,role:getRole()};localStorage.setItem(LOCAL_STATE_KEY,JSON.stringify(localState))}
function queueRemoteSave(shared){if(location.protocol==="file:")return;clearTimeout(remoteSyncTimer);remoteSyncTimer=setTimeout(()=>saveRemoteState(shared),350)}
async function saveRemoteState(shared){try{const res=await fetch(API_STATE_URL,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({state:shared})});if(!res.ok)throw new Error(`HTTP ${res.status}`);remoteSyncReady=true}catch(e){remoteSyncReady=false;console.warn("后台同步失败，已保留本机数据",e)}}
async function hydrateRemoteState(){if(location.protocol==="file:")return;try{const res=await fetch(API_STATE_URL,{headers:{"Accept":"application/json"}});if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();remoteSyncReady=true;if(data&&data.state){applyStateSnapshot(data.state);renderAfterStateLoad()}else{queueRemoteSave(makeSharedStateSnapshot())}}catch(e){remoteSyncReady=false;console.warn("后台数据读取失败，继续使用本机数据",e)}}
function saveState(show=true){collectCurrentChecklist();const shared=makeSharedStateSnapshot();saveLocalState(shared);queueRemoteSave(shared);if(show)showToast(remoteSyncReady?"已保存并同步到后台":"已保存到本机，后台同步中")}
function loadState(){const raw=localStorage.getItem(LOCAL_STATE_KEY);if(!raw)return;try{applyStateSnapshot(JSON.parse(raw),{includeUser:true})}catch(e){console.warn("本地保存数据读取失败",e)}}
function enterSystem(name,role){appState.user={name,role};roleSelect.value=role;document.body.classList.remove("login-pending");applyPermissions();saveState(false)}
function applyPermissions(){const r=getRole(),rules=roleRules[r];updateTopbarIdentity();roleNote.textContent=rules.note;userNote.textContent=`当前用户：${currentUserName()}（${rules.label}）`;renderAllDynamic();renderChecklist(currentProcessTab);renderFeedbacks()}
function approveItem(type,index){if(!canReview(getRole(),type))return showToast("当前角色不能审核");if(type==="plan"){appState.plans[index].status="负责人已确认";appState.plans[index].auditStatus="负责人已确认"}if(type==="risk"){appState.risks[index].status="已闭环";appState.risks[index].auditStatus="负责人已确认"}renderAllDynamic();saveState(false);showToast("已审核通过")}
function rejectItem(type,index){if(!canReview(getRole(),type))return showToast("当前角色不能退回");if(type==="plan"){appState.plans[index].status="退回整改";appState.plans[index].auditStatus="负责人退回"}if(type==="risk"){appState.risks[index].status="退回整改";appState.risks[index].auditStatus="负责人退回"}renderAllDynamic();saveState(false);showToast("已退回整改")}
loginBtn.addEventListener("click",()=>{enterSystem(loginName.value.trim()||"未命名用户",loginRole.value);showToast("登录成功")});logoutBtn.addEventListener("click",()=>{appState.user=null;document.body.classList.add("login-pending");showToast("已退出")});document.querySelectorAll(".nav button").forEach(b=>b.addEventListener("click",()=>switchView(b.dataset.view)));roleSelect.addEventListener("change",()=>{if(appState.user)appState.user.role=getRole();applyPermissions();saveState(false)});saveBtn.addEventListener("click",()=>saveState(true));
checkSpan.addEventListener("change",()=>{renderChecklist(currentProcessTab);saveState(false)});projectName?.addEventListener("input",()=>updateTopbarIdentity());planSpan?.addEventListener("change",()=>updateEntryLocks());riskPosition?.addEventListener("input",()=>updateEntryLocks());document.querySelectorAll("[data-process-tab]").forEach(tab=>tab.addEventListener("click",()=>{if(tab.disabled)return showToast("请先完成并确认前置工序");collectCurrentChecklist();renderChecklist(tab.dataset.processTab);saveState(false)}));
submitCheck.addEventListener("click",()=>{if(!canSubmit(getRole(),"process"))return showToast("施工进展由现场管理人员提交，项目负责人只审核");if(isProcessConfirmed(checkSpan.value,currentProcessTab))return showToast("该工序已由负责人确认，不能再次修改");if(!isProcessStageEnabled(checkSpan.value,currentProcessTab))return showToast("请先完成并确认前置工序");collectCurrentChecklist({keepStatus:false});const c=getCurrentCheck();c.submitter=currentUserName();c.businessStatus="管理人员已提交";c.auditStatus="待负责人审核";appState.processChecks[checkKey()]=c;syncSpanFlowFromProcess(checkSpan.value);renderChecklist(currentProcessTab);renderAllDynamic();saveState(false);showToast("工序检查已提交，待负责人审核")});
approveCheck.addEventListener("click",()=>{if(!canReview(getRole(),"process"))return showToast("只有项目负责人可以审核确认");if(!isPendingStatus(getCurrentCheck().auditStatus))return showToast("当前工序没有待审核内容");collectCurrentChecklist();const c=getCurrentCheck();c.businessStatus="负责人已确认";c.auditStatus="负责人已确认";c.reviewer=currentUserName();c.reviewComment=checkReviewComment.value||"同意";appState.processChecks[checkKey()]=c;syncSpanFlowFromProcess(checkSpan.value);renderChecklist(currentProcessTab);renderAllDynamic();saveState(false);showToast("工序检查已审核通过")});
rejectCheck.addEventListener("click",()=>{if(!canReview(getRole(),"process"))return showToast("只有项目负责人可以退回整改");if(!isPendingStatus(getCurrentCheck().auditStatus))return showToast("当前工序没有待审核内容");const c=getCurrentCheck();c.businessStatus="退回整改";c.auditStatus="负责人退回";c.reviewer=currentUserName();c.reviewComment=checkReviewComment.value||"请补充整改说明";appState.processChecks[checkKey()]=c;syncSpanFlowFromProcess(checkSpan.value);renderChecklist(currentProcessTab);renderAllDynamic();saveState(false);showToast("工序检查已退回整改")});
addSpanBtn.addEventListener("click",()=>{if(getRole()!=="leader")return showToast("只有项目负责人可维护桥跨台账");const tr=document.createElement("tr");tr.innerHTML=`<td>第 20 跨附属</td><td>19#-20#</td><td>湿接缝、横隔板、防撞墙</td><td>Ⅲ级封锁</td><td>模板、防坠落、防漏浆</td><td><span class="tag gray">新建</span></td>`;spanBody.appendChild(tr);saveState(false);showToast("桥跨记录已新增并保存")});
addPlan.addEventListener("click",()=>{if(!canSubmit(getRole(),"plan"))return showToast("作业计划由现场管理人员提交，项目负责人只审核");if(!canEditByTimeline({span:planSpan.value}))return showToast("前序桥跨未完成，不能提交该计划");appState.plans.unshift({purpose:planPurpose.value,span:planSpan.value,type:planType.value,duration:planDuration.value,power:planPower.value,coord:planCoord.value,status:"管理人员已提交",auditStatus:"待负责人审核"});renderAllDynamic();saveState(false);showToast("计划已提交，待负责人审核")});
toggleRiskForm?.addEventListener("click",()=>{if(!canSubmit(getRole(),"risk"))return showToast("只有现场管理人员可以提交隐患整改");riskFormOpen=!riskFormOpen;updateRiskFormVisibility()});addRisk.addEventListener("click",()=>{if(!canSubmit(getRole(),"risk"))return showToast("隐患整改由现场管理人员提交，项目负责人只审核");if(!canEditByTimeline({position:riskPosition.value}))return showToast("前序桥跨未完成，不能提交该隐患进展");let st="管理人员已提交";appState.risks.unshift({type:riskType.value,position:riskPosition.value,desc:riskDesc.value,owner:riskOwner.value,due:riskDue.value,status:st,auditStatus:"待负责人审核"});riskFormOpen=false;renderAllDynamic();saveState(false);showToast("隐患处理结果已提交，待负责人审核")});
document.addEventListener("input",e=>{const p=e.target.dataset.plan;if(p!==undefined){if(!canSubmit(getRole(),"plan"))return;appState.plans[+p][e.target.dataset.field]=e.target.innerText.trim();appState.plans[+p].status="管理人员已提交";appState.plans[+p].auditStatus="待负责人审核";renderReviewCenter();saveState(false)}});
document.addEventListener("change",e=>{const r=e.target.dataset.riskStatus;if(r!==undefined){if(!canSubmit(getRole(),"risk"))return;if(!isManagerRiskValue(e.target.value)){renderRisks();return showToast("该隐患状态不能由管理人员选择")}appState.risks[+r].status=e.target.value;appState.risks[+r].auditStatus=e.target.value==="管理人员已提交"?"待负责人审核":"未提交";renderAllDynamic();saveState(false)}});
document.addEventListener("click",e=>{const key=e.target.closest("[data-review-jump]")?.dataset.reviewJump;if(key){jumpToReviewItem(key);return}if(e.target.id==="reviewToggle"){reviewPanel.classList.toggle("open");return}const fj=e.target.dataset.flowJump;if(fj!==undefined){const flow=appState.spanFlows[+fj];switchView("process");checkSpan.value=flow.span;currentProcessTab=e.target.dataset.tab||nextFlowTab(flow.span);renderChecklist(currentProcessTab);return}const ps=e.target.dataset.planSubmit;if(ps!==undefined){if(!canSubmit(getRole(),"plan"))return showToast("作业计划由现场管理人员提交");if(isFinalConfirmedStatus(appState.plans[+ps].auditStatus)||isFinalConfirmedStatus(appState.plans[+ps].status))return showToast("该计划已由负责人确认，不能再次修改");appState.plans[+ps].status="管理人员已提交";appState.plans[+ps].auditStatus="待负责人审核";renderAllDynamic();saveState(false);showToast("计划变更已提交审核")}const pa=e.target.dataset.planApprove;if(pa!==undefined)approveItem("plan",+pa);const pr=e.target.dataset.planReject;if(pr!==undefined)rejectItem("plan",+pr);const rs=e.target.dataset.riskSubmit;if(rs!==undefined){if(!canSubmit(getRole(),"risk"))return showToast("隐患整改由现场管理人员提交");if(isFinalConfirmedStatus(appState.risks[+rs].auditStatus)||isFinalConfirmedStatus(appState.risks[+rs].status))return showToast("该隐患已由负责人确认，不能再次修改");appState.risks[+rs].status="管理人员已提交";appState.risks[+rs].auditStatus="待负责人审核";renderAllDynamic();saveState(false);showToast("隐患状态已提交审核")}const ra=e.target.dataset.riskApprove;if(ra!==undefined)approveItem("risk",+ra);const rr=e.target.dataset.riskReject;if(rr!==undefined)rejectItem("risk",+rr);const fba=e.target.dataset.feedbackApprove;if(fba!==undefined){if(!canReview(getRole(),"feedback"))return showToast("只有项目负责人可以审核反馈");appState.feedbacks[+fba].status="审核通过";appState.feedbacks[+fba].reviewer=currentUserName();appState.feedbacks[+fba].reviewComment="同意，纳入现场闭环跟踪";renderFeedbacks();renderAllDynamic();saveState(false);showToast("问题反馈已审核通过")}const fbr=e.target.dataset.feedbackReject;if(fbr!==undefined){if(!canReview(getRole(),"feedback"))return showToast("只有项目负责人可以退回反馈");appState.feedbacks[+fbr].status="退回整改";appState.feedbacks[+fbr].reviewer=currentUserName();appState.feedbacks[+fbr].reviewComment="退回整改，请现场补充处置情况";renderFeedbacks();renderAllDynamic();saveState(false);showToast("问题反馈已退回整改")}});
feedbackToggle.addEventListener("click",()=>feedbackPanel.classList.toggle("open"));submitFeedback.addEventListener("click",()=>{if(!canSubmit(getRole(),"feedback"))return showToast("项目负责人不能提交反馈，请审核下方反馈");const txt=feedbackText.value.trim();if(!txt)return showToast("请填写具体问题");appState.feedbacks.unshift({name:feedbackName.value.trim()||currentUserName(),date:feedbackDate.value,span:feedbackSpan.value,text:txt,status:"待负责人审核",reviewer:"",reviewComment:""});feedbackText.value="";renderFeedbacks();renderAllDynamic();saveState(false);showToast("问题反馈已提交，待负责人审核")});
function wordEsc(value){return String(value??"").replace(/[&<>]/g,s=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[s])).replace(/\r?\n/g,"<br>")}
function dateToken(){const d=new Date(),pad=n=>String(n).padStart(2,"0");return `${d.getFullYear()}${pad(d.getMonth()+1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}`}
function wordTable(rows){return `<table><tbody>${rows.map(row=>`<tr>${row.map(cell=>`<td>${wordEsc(cell)}</td>`).join("")}</tr>`).join("")}</tbody></table>`}
function makeWordDocument(title,sections){return `<!doctype html><html><head><meta charset="utf-8"><title>${wordEsc(title)}</title><style>body{font-family:"Microsoft YaHei",SimSun,Arial,sans-serif;font-size:12pt;color:#1d2523}h1{font-size:20pt;text-align:center;margin:0 0 18pt}h2{font-size:14pt;margin:14pt 0 8pt}.meta{color:#64716d;margin-bottom:12pt}table{border-collapse:collapse;width:100%;margin-bottom:14pt}td,th{border:1px solid #666;padding:6pt;vertical-align:top}tr:first-child td{font-weight:bold;background:#eaf2ef}</style></head><body><h1>${wordEsc(title)}</h1><div class="meta">导出时间：${new Date().toLocaleString()}　导出人：${wordEsc(currentUserName())}</div>${sections.map(section=>`<h2>${wordEsc(section.title)}</h2>${wordTable(section.rows)}`).join("")}</body></html>`}
function downloadWordFile(filename,content){const blob=new Blob(["\ufeff"+content],{type:"application/msword;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),800)}
function exportProjectLedger(){const rows=[["桥跨","墩号","作业内容","施工类别","控制重点","状态"],...Array.from(spanBody.querySelectorAll("tr")).map(tr=>Array.from(tr.cells).map(td=>td.textContent.trim()))],metaRows=[["项目名称",projectName.value],["铁路里程",railMile.value],["防护车站",station.value]];downloadWordFile(`项目桥跨台账-${dateToken()}.doc`,makeWordDocument("项目桥跨台账",[{title:"项目基础信息",rows:metaRows},{title:"桥跨台账",rows}]));showToast("项目桥跨台账 Word 文件已导出")}
function exportProcessChecks(){const rows=[["桥跨","工序","检查人","检查日期","检查项","检查结果","备注","工序状态","审核状态","提交人","审核人","审核意见"]];Object.values(appState.processChecks).forEach(c=>{(c.items||[]).forEach(item=>rows.push([c.span,tabLabel[c.tab]||c.tab,c.checker,c.date,item.item,item.status,item.remark,c.businessStatus,c.auditStatus,c.submitter,c.reviewer,c.reviewComment]))});downloadWordFile(`工序检查表-${dateToken()}.doc`,makeWordDocument("工序检查表",[{title:"工序检查记录",rows}]));showToast("工序检查表 Word 文件已导出")}
function exportRiskLedger(){const rows=[["风险类型","位置","整改要求","责任人","期限","业务状态","审核状态"]];appState.risks.forEach(r=>rows.push([r.type,r.position,r.desc,r.owner,r.due,r.status,r.auditStatus]));downloadWordFile(`隐患整改台账-${dateToken()}.doc`,makeWordDocument("隐患整改台账",[{title:"隐患整改记录",rows}]));showToast("隐患整改台账 Word 文件已导出")}
function exportEmergencyContacts(){const rows=[["岗位","姓名","联系方式","职责"],["项目负责人",appState.user?.role==="leader"?currentUserName():"项目负责人","","审核施工进展、退回整改、确认闭环"],["现场管理人员",appState.user?.role==="manager"?currentUserName():"现场管理人员","","提交工序、计划、隐患整改进展"],["施工人员",appState.user?.role==="worker"?currentUserName():"施工人员","","查看信息、提交现场问题反馈"],["驻站联络员","驻站联络员","","封锁命令传达、驻站协调"],["现场防护员","现场防护员","","邻营作业防护、现场盯控"],["设备负责人","设备负责人","","架桥机、运梁车、吊具状态检查"]];downloadWordFile(`应急联络表-${dateToken()}.doc`,makeWordDocument("应急联络表",[{title:"应急联络人员",rows}]));showToast("应急联络表 Word 文件已导出")}
function exportDocument(name){saveState(false);const exporters={"项目桥跨台账":exportProjectLedger,"工序检查表":exportProcessChecks,"隐患整改台账":exportRiskLedger,"应急联络表":exportEmergencyContacts};const fn=exporters[name];if(!fn)return showToast("暂不支持该资料导出");fn()}
document.querySelectorAll("[data-export]").forEach(btn=>btn.addEventListener("click",()=>exportDocument(btn.dataset.export)));
loadState();syncProcessChecksFromSpanFlows();renderAllDynamic();renderChecklist("pre");renderFeedbacks();if(appState.user){document.body.classList.remove("login-pending");loginName.value=appState.user.name||"";loginRole.value=appState.user.role||getRole();roleSelect.value=appState.user.role||getRole()}applyPermissions();hydrateRemoteState();
window.__auditPrototype={getPendingReviewItems,getTrackingItems,getFloatingItems,canView,canSubmit,canReview,canEditByTimeline,reset(){localStorage.clear();appState={processChecks:makeDefaultProcessChecks(),feedbacks:[],user:null,plans:clone(defaultPlans),spanFlows:clone(defaultSpanFlows),risks:clone(defaultRisks)};currentProcessTab="pre";document.body.classList.add("login-pending");roleSelect.value="manager";renderAllDynamic();renderChecklist("pre");renderFeedbacks();return true}};